// <auto-generated />
using System;
using GameLauncher.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameLauncher.DAL.Migrations
{
    [DbContext(typeof(GameLauncherContext))]
    [Migration("20240605154919_GenreMetaDataFix")]
    partial class GenreMetaDataFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("CollectionItem", b =>
                {
                    b.Property<Guid>("CollectionsID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemsID")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionsID", "ItemsID");

                    b.HasIndex("ItemsID");

                    b.ToTable("CollectionItem");
                });

            modelBuilder.Entity("DevelloppeurItem", b =>
                {
                    b.Property<Guid>("DevelloppeursID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemsID")
                        .HasColumnType("TEXT");

                    b.HasKey("DevelloppeursID", "ItemsID");

                    b.HasIndex("ItemsID");

                    b.ToTable("DevelloppeurItem");
                });

            modelBuilder.Entity("EditeurItem", b =>
                {
                    b.Property<Guid>("EditeursID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemsID")
                        .HasColumnType("TEXT");

                    b.HasKey("EditeursID", "ItemsID");

                    b.HasIndex("ItemsID");

                    b.ToTable("EditeurItem");
                });

            modelBuilder.Entity("GameLauncher.Models.Collection", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fanart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("GameLauncher.Models.Develloppeur", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Develloppeurs");
                });

            modelBuilder.Entity("GameLauncher.Models.Editeur", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Editeurs");
                });

            modelBuilder.Entity("GameLauncher.Models.Genre", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("GameLauncher.Models.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artwork")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LUPlatformesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LUProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NbStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LUPlatformesId");

                    b.HasIndex("LUProfileId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameLauncher.Models.LUEmulateur", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LUPlatformesID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LUPlatformesID");

                    b.ToTable("Emulateurs");
                });

            modelBuilder.Entity("GameLauncher.Models.LUPlatformes", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Databases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IgdbId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LUProfileID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LUProfileID");

                    b.ToTable("Platformes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("e2e0968e-0987-4b58-8115-a9daf99551a5"),
                            CodeName = "Steam",
                            Databases = "",
                            Name = "Steam"
                        },
                        new
                        {
                            ID = new Guid("88cd4887-8092-4c12-bdb6-29edfbce7cb4"),
                            CodeName = "Epic",
                            Databases = "",
                            Name = "Epic Games Store"
                        },
                        new
                        {
                            ID = new Guid("baf16d30-0eb6-447f-b0a2-a91e3fe68721"),
                            CodeName = "EA Play",
                            Databases = "",
                            Name = "EA Origin"
                        });
                });

            modelBuilder.Entity("GameLauncher.Models.LUProfile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LUEmulateurId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartupArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartupExecutable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LUEmulateurId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GameLauncher.Models.MetadataGenre", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GenreId");

                    b.ToTable("MetadataGenres");
                });

            modelBuilder.Entity("GenreItem", b =>
                {
                    b.Property<Guid>("GenresID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemsID")
                        .HasColumnType("TEXT");

                    b.HasKey("GenresID", "ItemsID");

                    b.HasIndex("ItemsID");

                    b.ToTable("GenreItem");
                });

            modelBuilder.Entity("CollectionItem", b =>
                {
                    b.HasOne("GameLauncher.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLauncher.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevelloppeurItem", b =>
                {
                    b.HasOne("GameLauncher.Models.Develloppeur", null)
                        .WithMany()
                        .HasForeignKey("DevelloppeursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLauncher.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EditeurItem", b =>
                {
                    b.HasOne("GameLauncher.Models.Editeur", null)
                        .WithMany()
                        .HasForeignKey("EditeursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLauncher.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameLauncher.Models.Item", b =>
                {
                    b.HasOne("GameLauncher.Models.LUPlatformes", "Platformes")
                        .WithMany()
                        .HasForeignKey("LUPlatformesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLauncher.Models.LUProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("LUProfileId");

                    b.Navigation("Platformes");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GameLauncher.Models.LUEmulateur", b =>
                {
                    b.HasOne("GameLauncher.Models.LUPlatformes", null)
                        .WithMany("Emulators")
                        .HasForeignKey("LUPlatformesID");
                });

            modelBuilder.Entity("GameLauncher.Models.LUPlatformes", b =>
                {
                    b.HasOne("GameLauncher.Models.LUProfile", null)
                        .WithMany("Platformes")
                        .HasForeignKey("LUProfileID");
                });

            modelBuilder.Entity("GameLauncher.Models.LUProfile", b =>
                {
                    b.HasOne("GameLauncher.Models.LUEmulateur", null)
                        .WithMany("Profiles")
                        .HasForeignKey("LUEmulateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameLauncher.Models.MetadataGenre", b =>
                {
                    b.HasOne("GameLauncher.Models.Genre", "Genre")
                        .WithMany("SubGenres")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GenreItem", b =>
                {
                    b.HasOne("GameLauncher.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLauncher.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameLauncher.Models.Genre", b =>
                {
                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameLauncher.Models.LUEmulateur", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("GameLauncher.Models.LUPlatformes", b =>
                {
                    b.Navigation("Emulators");
                });

            modelBuilder.Entity("GameLauncher.Models.LUProfile", b =>
                {
                    b.Navigation("Platformes");
                });
#pragma warning restore 612, 618
        }
    }
}
